### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by msajharder** [BuiltBrokenModding/ICBM#81]
I am receiving the following crash after installing the latest builds.

---- Minecraft Crash Report ----
// Sorry :(

Time: 2/26/15 4:08 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.item.crafting.CraftingManager.func_92103_a(CraftingManager.java:230)
	at cpw.mods.fml.common.registry.GameRegistry.addShapedRecipe(GameRegistry.java:244)
	at com.builtbroken.icbm.content.launcher.TileSmallLauncher.onPostInit(TileSmallLauncher.java:72)
	at com.builtbroken.mc.core.registry.ModManager.firePostInit(ModManager.java:345)
	at com.builtbroken.mc.lib.mod.AbstractMod.postInit(AbstractMod.java:68)
	at com.builtbroken.icbm.ICBM.postInit(ICBM.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.crafting.CraftingManager.func_92103_a(CraftingManager.java:230)
	at cpw.mods.fml.common.registry.GameRegistry.addShapedRecipe(GameRegistry.java:244)
	at com.builtbroken.icbm.content.launcher.TileSmallLauncher.onPostInit(TileSmallLauncher.java:72)
	at com.builtbroken.mc.core.registry.ModManager.firePostInit(ModManager.java:345)
	at com.builtbroken.mc.lib.mod.AbstractMod.postInit(AbstractMod.java:68)
	at com.builtbroken.icbm.ICBM.postInit(ICBM.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 413037712 bytes (393 MB) / 1683488768 bytes (1605 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 74 mods loaded, 74 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	PacketLogger{0.0.1} [PacketLogger] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	tickDynamic{0.1.4} [Tick Dynamic] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	appliedenergistics2{rv1-stable-1} [Applied Energistics 2] (appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeMultipart{1.1.1.321} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	chisel{2.3.5.31} [Chisel 2] (Chisel2-2.3.5.31.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CoFHCore{1.7.10R3.0.0RC2} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC2-195.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IC2{2.2.684-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.684-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalFoundation{1.7.10R1.0.0RC3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC3-56.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalExpansion{1.7.10R4.0.0RC2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0RC2-129.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V4c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded{1.7.10R2.8.0RC7} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	EnderIO{1.7.10-2.2.7.325} [Ender IO] (EnderIO-1.7.10-2.2.7.325.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Waila{1.5.8} [Waila] (Waila-1.5.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	extracells{2.1.37} [ExtraCells] (ExtraCells-1.7.10-2.1.37b62.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	McMultipart{1.1.1.321} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IC2NuclearControl{2.1.2a} [Nuclear Control 2] (IC2NuclearControl-2.1.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	VoltzEngine{0.3.2} [Voltz Engine] (VoltzEngine-1.7.10-0.3.2b187-dev.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	icbm{2.4.0.172} [ICBM] (ICBM-1.7.10-2.4.0b172-dev.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
	iChunUtil{4.1.3} [iChunUtil] (iChunUtil-4.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (magicalcrops-1.7.10_0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC7} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC7} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC7} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC7} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC7} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC7} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC7} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC7} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC7} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC7} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC7} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC7} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC7} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC7} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC7} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC7} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC7} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC7} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC7} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	moreplayermodels{1.7.10b} [MorePlayerModels] (MorePlayerModels_1.7.10b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NetherOres{1.7.10R2.3.0RC4} [Nether Ores] (NetherOres-[1.7.10]2.3.0RC4-4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	RotaryCraft{Gamma} [RotaryCraft] (RotaryCraft 1.7.10 V4c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ReactorCraft{beta} [ReactorCraft] (ReactorCraft 1.7.10 V4c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	RopesPlus{1.6.3} [Ropes+] (RopePlus-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AS_Ruins{14.7} [Ruins Spawning System] (Ruins-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	supercraftingframe{1.7.10.2} [Super Crafting Frame] (supercraftingframe-1.7.10.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Sync{4.0.0} [Sync] (Sync-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalDynamics{1.7.10R1.0.0RC2} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0RC2-77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	witchery{0.22.0} [Witchery] (witchery-1.7.10-0.22.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeMicroblock{1.1.1.321} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OpenModsLib crash transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED],[map_gen_fix:ENABLED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
	AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
	CoFHCore: -[1.7.10]3.0.0RC2-195
	Mantle Environment: Environment healthy.
	ThermalFoundation: -[1.7.10]1.0.0RC3-56
	ThermalExpansion: -[1.7.10]4.0.0RC2-129
	MineFactoryReloaded: -[1.7.10]2.8.0RC7-71
	NetherOres: Lacking version information.
	ThermalDynamics: -[1.7.10]1.0.0RC2-77
	Stencil buffer state: Function set: GL30, pool: forge, bits: 2
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:OFF, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 660 Ti/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (8)

**Comment by Hennamann** [comment]
It seems to be a crafting error. Could you try running these builds without any other mods, does it still crash? And what version of ICBM and voltz engine are you running?

**Comment by msajharder** [comment]
ICBM-1.7.10-2.4.0b172-dev.jar
VoltzEngine-1.7.10-0.3.2b187-dev.jar

Sure, i would be happy to isolate these mods. Give me a few minutes.

**Comment by TYKUHN2** [comment]
I am having the same issue. Unless it has been fixed I believe it may be caused by a reciepe conflict with other mods. Try removing mods including circut boards, it may fix it but no promises.

**Comment by msajharder** [comment]
Game starts fine with those two mods isolated.

**Comment by msajharder** [comment]
Crash invoked when industrialcraft-2-2.2.684-experimental.jar placed back into mods folder.

**Comment by Hennamann** [comment]
We will look into why this recipe conflict exists, since this is solved i will close it.

**Comment by msajharder** [comment]
Happy hunting. Please let me know if you need anything else.

**Comment by DarkGuardsman** [comment]
Update Voltz Engine as i thought i caught this error already. Its a problem with the UniversalRecipe handler which badly needs recoded. I made a slight patch for it that checks for Null items in our recipes. If it finds a null it replaces it with fire. Which isn't a solution but does prevent the crash from happening. Especially with the ICBM launcher trying to use IC2 circuits

**Comment by Hennamann** [comment]
He seems to already have the latest version of VE available on Builtbroken.com... Time for a new build perhaps?

**Comment by mwardrop** [comment]
We are attempting to add ICBM to the direwolf20 1.7.10 mod pack and still experiencing this issue with VE build 0.3.2-187 and ICBM build 2.4.0-172.

**Comment by Hennamann** [comment]
Direwolf20 1.7.10 contains industrialcraft 2, we are working om the issue.

**Comment by mwardrop** [comment]
Thanks for the quick reply, you guys rock!

I'll look for the future build.

**Comment by DarkGuardsman** [comment]
Ok issue is fixed. I made sure to install IC2 in my workspace and test. Turns out i neglected to set the recipe to accept OreDictionary items. So when IC2 was installed it attempted to use circuits threw the ore dictionary. Which resulted in a NPE since the MC default recipe system can't handle string values.

**Comment by TYKUHN2** [comment]
I am assuming this means I can finally debug my modpack? :smiley:

**Comment by Hennamann** [comment]
As the error is fixed, yes!

**Comment by fatyg5** [comment]
I'm having this error, but can't seem to find an updated version to fix it. Is there anywhere I could get this, as I see it has been fixed?

**Comment by dmodoomsirius** [comment]
@fatyg5 http://builtbroken.com/pages/icbm/1.7/downloads.php

**Comment by fatyg5** [comment]
Thank you.
